language: node_js

node_js:
  - '9.11.1'

env:
  global:
    - CC_TEST_REPORTER_ID=6a8e8207cb4d9f36061caa08ee3bd6584d55c378404543e8b10699946b6b58bf

script:
  - npm run test

cache: 
  npm: true
  directories:
    - 'node_modules'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
after_success:
  - npm run coverage
  